IALDashboard/Controllers/RecoveryController.cs
using ClosedXML.Excel;
using IALDashboard.DAL;
using Newtonsoft.Json;
using System;
using System.Data;
using System.Globalization;
using System.IO;
using System.Web.Mvc;

namespace IALDashboard.Controllers
{
    [Filters.AuthorizedUser]
    public class RecoveryController : Controller
    {
        // GET: Recovery
        public ActionResult CollectionReport()
        {
            return View();
        }

        //-------------------------------RO SHEET-------------------------------
        public ActionResult RoSheet()
        {
            ViewBag.actionName = "RO Sheet";
            string zone_name = "";
            DataTable dt_ro = new Collection_DAL().ROInfo(zone_name);
            DataTable dt_zone = new Collection_DAL().ZoneInfo();
            ViewBag.rolist = dt_ro;
            ViewBag.zonelist = dt_zone;
            return View();
        }


        [HttpPost]
        public string GetJsonROList(string from_date, string ro_code, string zone_name)
        {
            from_date = from_date + "-01";

            DataTable dt = new Collection_DAL().ROSheet(from_date, ro_code, zone_name);

            string JSONString = string.Empty;
            JSONString = JsonConvert.SerializeObject(dt);
            return JSONString;
        }

        [HttpPost]
        public string GetJsonROListByZone(string from_date, string zone_name)
        {
            from_date = from_date + "-01";

            DataTable dt = new Collection_DAL().ROListByZone(from_date, zone_name);

            string JSONString = string.Empty;
            JSONString = JsonConvert.SerializeObject(dt);
            return JSONString;
        }


        [HttpGet]
        public ActionResult ExportROSheet(string from_date, string ro_code, string zone_name)
        {
            from_date = from_date + "-01";

            DataTable ro_list = new Collection_DAL().ROListByZone(from_date, zone_name);

            DataTable ro_summary = new DataTable();


            DataTable dt = new Collection_DAL().ROSheet(from_date, ro_code, zone_name);

            DateTime formatted_date = DateTime.ParseExact(from_date, "yyyy-MM-dd", null);

            String formatted_from_date = formatted_date.ToString("MMMM, yyyy");


            using (XLWorkbook wb = new XLWorkbook())
            {
                foreach (DataRow row in ro_list.Rows)
                {
                    DataRow[] rodt = dt.Select("RO_CODE ='" + row["RO_CODE"] + "'");

                    if (rodt.Length != 0)
                    {
                        ro_summary = new Collection_DAL().ROSummaryByROCode(from_date, row["RO_CODE"].ToString());

                        var ws = wb.Worksheets.Add(row["RO_NAME"].ToString());

                        ws.Column("A").Width = 5;
                        ws.Column("B").Width = 8;
                        ws.Column("C").Width = 12;
                        ws.Column("E").Width = 16;
                        ws.Column("F").Width = 10;
                        ws.Column("J").Width = 12;
                        ws.Column("M").Width = 12;

                        ws.Range("A1:P5").Style.Alignment.SetHorizontal(XLAlignmentHorizontalValues.Center);
                        ws.Cell("A1").Value = "Ifad Autos Ltd (Monthly Target Sheet)";
                        ws.Range("A1:P1").Merge().Style.Font.SetBold().Font.FontSize = 14;

                        ws.Cell("A2").Value = "Month: " + formatted_from_date;
                        ws.Range("A2:P2").Merge().Style.Font.SetBold().Font.FontSize = 12;

                        ws.Cell("A3").Value = "RO CODE: " + row["RO_CODE"].ToString() + "RO Name: " + row["RO_NAME"].ToString() + " ZONE: " + zone_name;
                        ws.Range("A3:P3").Merge().Style.Font.SetBold().Font.FontSize = 12;

                        ws.Cell("A5").Value = "SL NO";
                        ws.Range("A5").Style.Font.SetBold().Font.FontSize = 12;

                        ws.Cell("B5").Value = "Order No";
                        ws.Range("B5").Style.Font.SetBold().Font.FontSize = 12;

                        ws.Cell("C5").Value = "Customer Name";
                        ws.Range("C5").Style.Font.SetBold().Font.FontSize = 12;

                        ws.Cell("D5").Value = "Registration No";
                        ws.Range("D5").Style.Font.SetBold().Font.FontSize = 12;

                        ws.Cell("E5").Value = "Model Name";

                        ws.Range("E5").Style.Font.SetBold().Font.FontSize = 12;

                        ws.Cell("F5").Value = "1st Date";
                        ws.Range("F5").Style.Font.SetBold().Font.FontSize = 12;

                        ws.Cell("G5").Value = "Term";
                        ws.Range("G5").Style.Font.SetBold().Font.FontSize = 12;

                        ws.Cell("H5").Value = "OP. Tar Inst Amt.";
                        ws.Range("H5").Style.Font.SetBold().Font.FontSize = 12;

                        ws.Cell("I5").Value = "EMI AMT.";
                        ws.Range("I5").Style.Font.SetBold().Font.FontSize = 12;

                        ws.Cell("J5").Value = "NO.Ovd";
                        ws.Range("J5").Style.Font.SetBold().Font.FontSize = 12;

                        ws.Cell("K5").Value = "MR COLL";
                        ws.Range("K5").Style.Font.SetBold().Font.FontSize = 12;

                        ws.Cell("L5").Value = "DP+DC Due";
                        ws.Range("L5").Style.Font.SetBold().Font.FontSize = 12;

                        ws.Cell("M5").Value = "INST DC";
                        ws.Range("M5").Style.Font.SetBold().Font.FontSize = 12;

                        ws.Cell("N5").Value = "Op. Ovd";
                        ws.Range("N5").Style.Font.SetBold().Font.FontSize = 12;

                        ws.Cell("O5").Value = "Monthly Coll";
                        ws.Range("O5").Style.Font.SetBold().Font.FontSize = 12;

                        ws.Cell("P5").Value = "Atten V";
                        ws.Range("P5").Style.Font.SetBold().Font.FontSize = 12;


                        int i = 0;
                        double SUB_EMI_AMOUNT = 0;
                        double SUB_TAR_INST_AMT = 0;
                        double SUB_NO_OF_OVERDUE = 0;
                        double SUB_MR_COLL = 0;
                        double SUB_DUE_DP_AND_DC = 0;
                        double SUB_INS_DC = 0;
                        double SUB_OVERDUE = 0;
                        double SUB_MONTHLY_COLL = 0;
                        double SUB_ATTEN_V = 0;
                        double SUB_OPENING_OVERDUE = 0;

                        foreach (DataRow record in rodt)
                        {
                            SUB_EMI_AMOUNT += Convert.ToDouble(record["EMI_AMOUNT"]);
                            SUB_TAR_INST_AMT += Convert.ToDouble(record["OP_TAR_INST_AMT"]);
                            SUB_NO_OF_OVERDUE += Convert.ToDouble(record["NO_OF_OVERDUE"]);
                            SUB_MR_COLL += Convert.ToDouble(record["MR_COLL"]);
                            SUB_DUE_DP_AND_DC += Convert.ToDouble(record["DUE_DP_AND_DC"]);
                            SUB_INS_DC += Convert.ToDouble(record["INS_DC"]);
                            SUB_OVERDUE += Convert.ToDouble(record["OVERDUE"]);
                            SUB_MONTHLY_COLL += Convert.ToDouble(record["MONTHLY_COLL"]);
                            SUB_ATTEN_V += Convert.ToDouble(record["ATTEN_V"]);
                            SUB_OPENING_OVERDUE += Convert.ToDouble(record["OPENING_OVERDUE"]);

                            ws.Cell("A" + (i + 6)).Value = i + 1;
                            ws.Cell("B" + (i + 6)).Value = record["ORDER_NO"].ToString();
                            ws.Cell("C" + (i + 6)).Value = record["CUSTOMER_NAME"].ToString();
                            ws.Cell("D" + (i + 6)).Value = record["REGNO"].ToString();
                            ws.Cell("E" + (i + 6)).Value = record["CATALOG_DESC"].ToString();
                            ws.Cell("F" + (i + 6)).Value = record["FSTINSAL_DATE"].ToString();
                            ws.Cell("G" + (i + 6)).Value = record["TERM"].ToString();
                            ws.Cell("H" + (i + 6)).Value = record["OP_TAR_INST_AMT"].ToString();
                            ws.Cell("I" + (i + 6)).Value = record["EMI_AMOUNT"].ToString();
                            ws.Cell("J" + (i + 6)).Value = record["NO_OF_OVERDUE"].ToString();
                            ws.Cell("K" + (i + 6)).Value = record["MR_COLL"].ToString();
                            ws.Cell("L" + (i + 6)).Value = record["DUE_DP_AND_DC"].ToString();
                            ws.Cell("M" + (i + 6)).Value = record["INS_DC"].ToString();
                            ws.Cell("N" + (i + 6)).Value = record["OPENING_OVERDUE"].ToString();
                            ws.Cell("O" + (i + 6)).Value = record["MONTHLY_COLL"].ToString();
                            ws.Cell("P" + (i + 6)).Value = record["ATTEN_V"].ToString();
                            i++;
                        }
                        ws.Cell("G" + (i + 6)).Value = "Sub Total";
                        ws.Cell("H" + (i + 6)).Value = SUB_TAR_INST_AMT.ToString();
                        ws.Cell("I" + (i + 6)).Value = SUB_EMI_AMOUNT.ToString();
                        ws.Cell("J" + (i + 6)).Value = SUB_NO_OF_OVERDUE.ToString();
                        ws.Cell("K" + (i + 6)).Value = SUB_MR_COLL.ToString();
                        ws.Cell("L" + (i + 6)).Value = SUB_DUE_DP_AND_DC.ToString();
                        ws.Cell("M" + (i + 6)).Value = SUB_INS_DC.ToString();
                        ws.Cell("N" + (i + 6)).Value = SUB_OPENING_OVERDUE.ToString();
                        ws.Cell("O" + (i + 6)).Value = SUB_MONTHLY_COLL.ToString();
                        ws.Cell("P" + (i + 6)).Value = SUB_ATTEN_V.ToString();


                        ws.Range("F" + (i + 6) + ":P" + (i + 6)).Style.Font.SetBold().Font.FontSize = 11;

IALDashboard/Views/Recovery/CollectionReport.cshtml
<div class="col-md-4">
    <!-- general form elements -->
    <div class="card card-primary">
        <!--
    <div class="card-header">
        <h3 class="card-title">Monthly Collection Report</h3>
    </div>
        -->
        <!-- /.card-header -->
        <!-- form start -->
        @using (Html.BeginForm("ExportCollectionReport", "Recovery", new { ReturnUrl = ViewBag.ReturnUrl }, FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
        {
            <div class="card-body">

                <label>Select Month</label>

                <div class="input-group">
                    <div class="input-group-prepend">
                        <span class="input-group-text"><i class="far fa-calendar-alt"></i></span>
                    </div>
                    <input class="form-control" type="month" name="from_date" required />
                    <!--<input id="datemask" type="text" class="form-control" data-inputmask-alias="datetime" data-inputmask-inputformat="mm/yyyy" data-mask>-->
                </div>

            </div>
            <!-- /.card-body -->

            <div class="card-footer">
                <button type="submit" class="btn btn-outline-primary btn-sm myPreLoader">Export to Excel</button>
            </div>
        }
    </div>
</div>
<!-- /.card -->

IALDashboard/Views/Recovery/RoSheet.cshtml
@{
    var rolist = ViewBag.rolist;
    var zonelist = ViewBag.zonelist;

    Layout = "~/Views/Shared/_Layout.cshtml";
}



    

        <div class="col-md-6 col-sm-12">
            <!-- general form elements -->
            <div class="card card-primary">
                @using (Html.BeginForm("ExportROSheet", "Recovery", FormMethod.Get))
                {

                    <!--
                           <div class="card-header">
                               <h3 class="card-title">Monthly RO Sheet</h3>
                           </div>
                           /.card-header -->
                    <!-- form start -->

                    <div class="card-body">

                        <div class="row">
                            <div class="form-group col-md-6">
                                <label>Select Month</label>
                                <div class="input-group">
                                    <div class="input-group-prepend">
                                        <span class="input-group-text"><i class="far fa-calendar-alt"></i></span>
                                    </div>
                                    <input class="form-control" type="month" name="from_date" required id="from-date" />
                                </div>
                            </div>
                            <div class="form-group col-md-6">
                                <label>Select Zone</label>
                                <select class="form-control" style="width: 100%;" name="zone_name" id="zoneName" required>
                                    <option selected="" value="">Select</option>
                                    @{
                                        foreach (System.Data.DataRow zone in zonelist.Rows)
                                        {
                                            <option value="@zone["ZONE_NAME"]">@zone["ZONE_NAME"]</option>
                                        }
                                    }
                                </select>
                            </div>

                            <div class="form-group col-md-6">
                                <label>Select RO</label>
                                <select class="form-control select2" style="width: 100%;" name="ro_code" id="ro-code">
                                    <option selected="" data-ro="" value="">Select</option>

                                    @{
                                        foreach (System.Data.DataRow ro in rolist.Rows)
                                        {
                                            <option data-ro="@ro["RO_NAME"]" value="@ro["RO_CODE"]">@ro["RO_CODE"] - @ro["RO_NAME"]</option>
                                        }
                                    }

                                </select>
                            </div>
                        </div>




                    </div>
                    <!-- /.card-body -->

                    <div class="card-footer">
                        <button id="btn-get-ro-sheet" class="btn btn-primary myPreLoader" type="button" style="display:none">Submit</button>
                        <input id="btn-export-to-excel" class="btn btn-outline-primary myPreLoader" type="submit" value="Export to Excel" />

                    </div>
                }
            </div>
          
        </div>
        <!-- /.card -->



        <div class="card col-sm-12 col-md-12" style="display:none">
            <div class="card-header">
                

            </div>
            <!-- /.card-header -->
            <div class="card-body">

                <div class="table">
                    <table id="ro-table" class="table-responsive table-striped nowrap">
                        <thead id="report-header">
                            <tr>
                                <th nowrap>SL No.</th>
                                <th nowrap>Order No</th>
                                <th nowrap>Customer Name</th>
                                <th nowrap>RO Name</th>
                                <th nowrap>Reg. No.</th>
                                <th nowrap>Model</th>
                                <th nowrap>1st EMI DT. </th>
                                <th nowrap>EMI AMT.</th>
                                <th nowrap>Target Inst. Amt.</th>
                                <th nowrap>No. of OVD.</th>
                                <th nowrap>MR Coll.</th>
                                <th nowrap>DP+DC Due</th>
                                <th nowrap>INST DC</th>
                                <th nowrap>Overdue</th>
                                <th nowrap>Monthly Coll.</th>
                                <th nowrap>Inst Coll.</th>
                                <th nowrap>Atten V.</th>
                            </tr>
                        </thead>
                        <tbody id="ro-tbody">
                        </tbody>
                        <tfoot>

                        </tfoot>
                    </table>
                </div>
            </div>
            <!-- /.card-body -->
        </div>
        <!-- /.card -->
 

<script>
    document.addEventListener('DOMContentLoaded', function () {
        document.getElementById('btn-export-to-excel').addEventListener('click', function () {
            setTimeout(function () { hidePreloader(); }, 1000);
        });


        document.getElementById('zoneName').addEventListener('change', function () {
            var from_date = document.getElementById('from-date').value;
            var zone_name = document.getElementById('zoneName').value;
            if (from_date == '') {
                alert('select month!');
                document.getElementById('zoneName').value = "";
            } else {
                (async () => {
                    const rawResponse = await fetch('GetJsonROListByZone', {
                        method: 'POST',
                        headers: {
                            'Accept': 'application/json',
                            'Content-Type': 'application/json'
                        },
                        body: JSON.stringify({ from_date: from_date, zone_name: zone_name })
                    });
                    const rolist = await rawResponse.json();
                    if (rolist.length == 0) {
                        alert("No RO Found!");
                    }
                    document.querySelector('#ro-code').innerHTML = '';
                    row = `<option value="">Select</option>`
                    rolist.forEach(ro => {
                        row += `<option value=${ro["RO_CODE"]}>${ro["RO_NAME"]}</option>`
                    });

                    document.querySelector('#ro-code').innerHTML = row;

                    console.log(rolist);
                })();
            }
        });
        
        
       @* document.getElementById('btn-get-ro-sheet___1').onclick = function () {

            var table = document.getElementById("ro-table");

            var from_date = document.getElementById('from-date').value;
            var ro_code = document.getElementById('ro-code').value;

            var zone_name = document.getElementById('zoneName').value;


            (async () => {
                const rawResponse = await fetch('GetJsonROList', {
                    method: 'POST',
                    headers: {
                        'Accept': 'application/json',
                        'Content-Type': 'application/json'
                    },
                    body: JSON.stringify({ from_date: from_date, ro_code: ro_code, zone_name: zone_name })
                });
                const rolist = await rawResponse.json();
                if (rolist.length == 0) {
                    alert("Please Set Apropriate Date and RO");
                }
                var i = 0;
                document.querySelector('#ro-tbody').innerHTML = '';
                rolist.forEach(ro => {
                    i += 1;
                    row = `<tr>
                                <td nowrap>${i}</td>
                                <td nowrap>${ro["ORDER_NO"]}</td>
                                <td nowrap>${ro["CUSTOMER_NAME"]}</td>
                                <td nowrap>${ro["RO_NAME"]}</td>
                                <td nowrap>${ro["REGNO"]}</td>
                                <td nowrap>${ro["CATALOG_DESC"]}</td>
                                <td nowrap>${ro["FSTINSAL_DATE"]}</td>
                                <td nowrap>${ro["EMI_AMOUNT"]}</td>
                                <td nowrap>${ro["TAR_INST_AMT"]}</td>
                                <td nowrap>${ro["NO_OF_OVERDUE"]}</td>
                                <td nowrap>${ro["MR_COLL"]}</td>
                                <td nowrap>${ro["DP_DC_PAYMENT"]}</td>
                                <td nowrap>${ro["INS_DC_PAYMENT"]}</td>
                                <td nowrap>${ro["OVERDUE"]}</td>
                                <td nowrap>${ro["MONTHLY_COLL"]}</td>
                                <td nowrap>${ro["INST_COLL"]}</td>
                                <td nowrap>${ro["ATTEN_V"]}</td>
                           </tr>`;
                    document.querySelector('#ro-tbody').innerHTML += row;

                });

                console.log(rolist);
                hidePreloader();


            })();

        }
*@





        








    });




</script>

<script>
</script>

IALDashboard/Views/Recovery/RoSummary.cshtml
@{
    var rolist = ViewBag.rolist;
    var zonelist = ViewBag.zonelist;

    Layout = "~/Views/Shared/_Layout.cshtml";
}


<div class="row">

    
        <div class="col-md-6">
            <!-- general form elements -->
            <div class="card card-primary">
                <!--   <div class="card-header">
          <h3 class="card-title">Monthly RO Summary</h3>
      </div>
      /.card-header -->
                <!-- form start -->
                @using (Html.BeginForm("ExportROSummary", "Recovery", FormMethod.Post))
                {
                    <div class="card-body">
                        <div class="row">
                            <div class="form-group col-md-6">
                                <label>Select Month</label>
                                <div class="input-group">
                                    <div class="input-group-prepend">
                                        <span class="input-group-text"><i class="far fa-calendar-alt"></i></span>
                                    </div>
                                    <input class="form-control" type="month" name="from_date" required id="from-date" />
                                </div>
                            </div>


                            <div class="form-group col-md-6">
                                <label>Select Zone</label>
                                <select class="form-control select2" style="width: 100%;" name="zone_name" id="zone-name">
                                    <option selected="" value="">Select</option>
                                    @{
                                        foreach (System.Data.DataRow zone in zonelist.Rows)
                                        {
                                            <option value="@zone["ZONE_NAME"]">@zone["ZONE_NAME"]</option>
                                        }
                                    }
                                </select>
                            </div>
                        </div>


                    </div>
                    <!-- /.card-body -->

                    <div class="card-footer">
                        <button id="btn-get-ro-summary" class="btn btn-primary btn-sm myPreLoader" type="button">Submit</button>
                        <input class="btn btn-outline-primary pull-right btn-sm" type="submit" value="Export to Excel" />
                    </div>
                }
            </div>
        </div>
        <!-- /.card -->
    </div>


        <div class="card">
       
            <!-- /.card-header -->
            <div class="card-body table-responsive">





                @*<button type="button" class="btn btn-block btn-outline-primary" onclick="tableToExcel('dailyStockReport', 'dailyStockReport')">Export to Excel</button>*@
                <div class="table">
                    <!--<table id="dailyStockReport" class="table table-bordered table-striped table-condensed display nowrap" style="width:100%">-->
                    <table id="ro-table" class="table-bordered table-striped" style="width:100%; font-size:small" width="100%">
                        <thead id="report-header">
                            <tr>
                                <th>SL No.</th>
                                <th>Zone Name</th>
                                <th>RO Code</th>
                                <th>RO Name</th>
                                <th>OP. Target Inst. Amt</th>
                                <th>Actual OP.Overdue</th>
                                <th>Monthly Coll</th>
                                <th>Inst Coll</th>
                                <th>OD Coll</th>
                                <th>Excell Coll</th>
                                <th>No. Veh</th>
                                <th>Attn Veh</th>
                                <th>Target Coll (%)</th>
                                <th>Inst. Coll (%)</th>
                                <th>Ovd. Coll (%)</th>
                                <th>Excess Coll (%)</th>
                                <th>Attn (%)</th>
                            </tr>
                        </thead>
                        <tbody id="ro-tbody">
                        </tbody>
                        <tfoot>

                        </tfoot>
                    </table>
                </div>
            </div>
            <!-- /.card-body -->
        </div>
        <!-- /.card -->


<script>

    document.addEventListener('DOMContentLoaded', function () {
        document.getElementById('btn-get-ro-summary').onclick = function () {

            var table = document.getElementById("ro-table");

            var from_date = document.getElementById('from-date').value;
            var zone_name = document.getElementById('zone-name').value;


            (async () => {
                const rawResponse = await fetch('GetJsonROSummary', {
                    method: 'POST',
                    headers: {
                        'Accept': 'application/json',
                        'Content-Type': 'application/json'
                    },
                    body: JSON.stringify({ from_date: from_date, zone_name : zone_name })
                });
                const roSummary = await rawResponse.json();
                if (roSummary.length == 0) {
                    alert("Please Set Apropriate Date and Zone");
                }

                var i = 0;
                document.querySelector('#ro-tbody').innerHTML = '';
                roSummary.forEach(rs => {
                    i += 1;
                    row = `<tr>
                                <td>${i}</td>
                                <td>${rs["ZONE_NAME"]}</td>
                                <td>${rs["RO_CODE"]}</td>
                                <td>${rs["RO_NAME"]}</td>
                                <td>${rs["OP_TAR_INST_AMT"]}</td>
                                <td>${rs["ACTUAL_OPENING_OVERDUE"]}</td>
                                <td>${rs["MONTHLY_COLL"]}</td>
                                <td>${rs["INST_COLL"]}</td>
                                <td>${rs["OD_COLECTION"]}</td>
                                <td>${rs["EXCESS_COLLECTION"]}</td>
                                <td>${rs["NO_OF_VEHICLE"]}</td>
                                <td>${rs["ATTEN_V"]}</td>
                                <td>${rs["TAR_COLL_PERCENT"]}</td>
                                <td>${rs["INST_COLL_PERCENT"]}</td>
                                <td>${rs["OVERDUE_COLL_PERCENT"]}</td>
                                <td>${rs["EXCESS_COLLECTION_PERCENT"]}</td>
                                <td>${rs["ATTEN_V_PERCENT"]}</td>
                           </tr>`;
                    document.querySelector('#ro-tbody').innerHTML += row;

                });

                
                hidePreloader();


            })();

        }

    });


</script>